export const screens = [
  {
    id: 1,
    title: "Homepage",
    color: "#4682B4",
    typeIcon: "1",
    icon: "home",
    link: "Home",
  },
  {
    id: 5,
    title: "Form",
    color: "#4682B4",
    typeIcon: "3",
    icon: "form",
    link: "Form",
  },
  {
    id: 9,
    title: "Login",
    color: "#4682B4",
    typeIcon: "6",
    icon: "login-variant",
    link: "Login",
  },
  {
    id: 10,
    title: "Profile (Protected page)",
    color: "#4682B4",
    typeIcon: "2",
    icon: "lock",
    link: "ProtectedPage",
  },
  {
    id: 12,
    title: "Theme settings",
    color: "#4682B4",
    typeIcon: "5",
    icon: "settings-sharp",
    link: "Theme",
  },
];
